fix: Upgrade Harvest to hide BIContractActivationWindow when needed
cozy/cozy-banks pull request #2487
Opened 2022-09-07 13:08 UTC by doubleface

2022-09-07 14:29 UTC, JF-Cozy approved these changes
les modifs de changelog sont ok ?

2022-09-15 06:11 UTC, Crash-- commented
ping @doubleface

2022-09-15 08:09 UTC, Crash-- commented
@JF-Cozy cette modif est déjà sur master ? Si oui on peut fermer cette PR, right?

2022-09-15 10:10 UTC, JF-Cozy requested changes
@doubleface on n'a pas reparlé de la branche 1.45.0, mais on s'est dit (cf Paper) qu'on la laisse tomber, elle ne doit plus vivre.

2022-09-15 10:19 UTC, JF-Cozy commented
> cette modif est déjà sur master ? Si oui on peut fermer cette PR, right?

Bon j'ai jeté un oeil, oui c'est sur master https://github.com/cozy/cozy-banks/pull/2485 et j'ai vérifié avec l'état actuel de master, c'est bien là.

Je close.

2022-09-15 10:19 UTC, closed without merging